lane_detection_node: 
  ros__parameters: 
    Hue_low : 18 
    Hue_high : 50 
    Saturation_low : 75 
    Saturation_high : 255 
    Value_low : 145 
    Value_high : 255 
    number_of_lines : 100 
    error_threshold : 0.16 
    Width_min : 15 
    Width_max : 112 
    gray_lower : 61 
    inverted_filter : 0 
    kernal_size : 3 
    erosion_itterations : 1 
    dilation_itterations : 4 
    crop_width_decimal  : 0.7 
    rows_to_watch_decimal  : 0.2 
    rows_offset_decimal  : 0.5
    camera_centerline : 0.55 
calibration_node: 
  ros__parameters: 
    Hue_low : 18 
    Hue_high : 50 
    Saturation_low : 75 
    Saturation_high : 255 
    Value_low : 145 
    Value_high : 255 
    number_of_lines : 100 
    error_threshold : 0.16 
    Width_min : 15 
    Width_max : 112 
    gray_lower : 61 
    inverted_filter : 0 
    kernal_size : 3 
    erosion_itterations : 1 
    dilation_itterations : 4 
    crop_width_decimal  : 0.7 
    rows_to_watch_decimal  : 0.2 
    rows_offset_decimal  : 0.5
    camera_centerline : 0.55 
lane_guidance_node: 
  ros__parameters: 
    Kp_steering : 0.8 
    Ki_steering : 0.0 
    Kd_steering : 0.0 
    zero_throttle  : -0.03200000000000003 
    max_throttle : 0.382 
    min_throttle : 0.363 
    error_threshold : 0.16 
    max_right_steering : 0.792 
    max_left_steering : -0.831 
vesc_twist_node: 
  ros__parameters: 
    max_potential_rpm : 20000 
    steering_polarity : 1 
    throttle_polarity : 1 
    zero_throttle  : -0.03200000000000003 
    max_throttle : 0.382
    min_throttle : 0.363 
    max_right_steering : 0.792 
    straight_steering : -0.21999999999999997 
    max_left_steering : -0.831 
adafruit_twist_node: 
  ros__parameters: 
    steering_polarity : 1 
    throttle_polarity : 1 
    zero_throttle  : -0.03200000000000003 
    max_throttle : 0.382
    min_throttle : 0.363 
    max_right_steering : 0.792 
    straight_steering : -0.21999999999999997 
    max_left_steering : -0.831 
